services:
  db:
    image: postgres:17-alpine
    container_name: peernet-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: peernet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d peernet"]
      interval: 10s
      timeout: 5s
      retries: 5

  tracker:
    build:
      context: .
      dockerfile: tracker/Dockerfile
    container_name: peernet-tracker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/peernet?sslmode=disable
      - TRACKER_PORT=8080
      - JWT_SECRET=a_very_secret_key
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    driver: bridge